version: '3.9'

services:
  divinemarkets-backend:
    build: .
    container_name: divinemarkets-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
